import {validateEntry,moveBlock,renderEntry} from '../samples/entry.js';
const q=id=>document.getElementById(id),key='nhur-public-entry-v1';const initial=()=>({version:1,blocks:[{id:'intro',type:'text',text:'Un Entorno para quienes comparten la curiosidad por crear.'},{id:'idea',type:'quote',text:'El formato también debe dejarte pensar.'},{id:'task',type:'checklist',text:'Probar teclado, foco y persistencia local.',checked:false}]});let entry=initial(),selected='intro';
try{const saved=localStorage.getItem(key);if(saved)entry=validateEntry(JSON.parse(saved));}catch{q('status').textContent='No se pudo restaurar la copia local. El ejemplo sigue disponible.';}
if(entry.blocks.length)selected=entry.blocks[0].id;
function refresh(){q('block').replaceChildren();for(const block of entry.blocks){const option=document.createElement('option');option.value=block.id;option.textContent=block.type+' / '+block.id;option.selected=block.id===selected;q('block').append(option);}const active=entry.blocks.find(b=>b.id===selected);q('text').value=active?.text??'';q('text').disabled=!active;const index=entry.blocks.findIndex(b=>b.id===selected);q('up').disabled=index<=0;q('down').disabled=index<0||index===entry.blocks.length-1;renderEntry(entry,q('preview'));q('json').textContent=JSON.stringify(entry,null,2);}
q('block').addEventListener('change',()=>{selected=q('block').value;refresh();});
q('text').maxLength=4000;q('text').addEventListener('input',()=>{entry=validateEntry({...entry,blocks:entry.blocks.map(b=>b.id===selected?{...b,text:q('text').value}:b)});renderEntry(entry,q('preview'));q('json').textContent=JSON.stringify(entry,null,2);});
for(const [id,delta] of [['up',-1],['down',1]])q(id).addEventListener('click',()=>{entry=moveBlock(entry,selected,delta);refresh();q('block').focus();q('status').textContent='Bloque movido. La selección conserva su identidad.';});
q('save').addEventListener('click',()=>{try{localStorage.setItem(key,JSON.stringify(entry));q('status').textContent='Guardado en este navegador.';}catch{q('status').textContent='El navegador no permite guardar. Tu edición sigue en esta sesión.';}});
q('reset').addEventListener('click',()=>{entry=initial();selected='intro';refresh();q('status').textContent='Ejemplo restaurado en la sesión. Guarda si quieres reemplazar la copia local.';});refresh();
